version: '3.8'

services:
  mcp-hub:
    build: 
      context: .
      dockerfile: Dockerfile
    image: aliyun-computenest/mcp-hub:latest
    container_name: mcp-hub
    ports:
      - "${APP_PORT:-9000}:80"
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-47.84.65.28}
      - PRIVATE_IP=${PRIVATE_IP:-192.168.1.100}
      - API_KEY=${API_KEY:-}
    volumes:
      # 挂载配置文件，方便修改
      - ./root/config.json:/usr/share/nginx/html/config.json:ro
      - ./root/pre-mcp-tools.json:/usr/share/nginx/html/config_detail.json:ro
      # 挂载自定义配置目录（可选）
      - ./config:/usr/share/nginx/html/config:ro
    restart: unless-stopped
    networks:
      - mcp-network
    labels:
      - "com.github.repo=aliyun-computenest/mcp-hub"
      - "com.docker.compose.project=mcp-hub"

networks:
  mcp-network:
    driver: bridge
    name: mcp-hub-network

volumes:
  mcp-config:
    driver: local
